# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='valid',
        ),
    ]
